# Generated by Django 5.1.1 on 2025-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
