# Generated by Django 5.1.1 on 2025-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_registereduser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
